
import Database.AuthenticationController;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class ForgetPasswordPage extends javax.swing.JFrame {

    /**
     * Creates new form ForgetPasswordPage
     */
    public ForgetPasswordPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel2 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                usernameField = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                newPasswordField = new javax.swing.JPasswordField();
                jLabel6 = new javax.swing.JLabel();
                question_input = new javax.swing.JTextField();
                changePasswordButton = new javax.swing.JButton();
                jLabel5 = new javax.swing.JLabel();
                loginBtn = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(0, 153, 51));
                jLabel2.setText("Forget Password");
                jLabel2.setToolTipText("");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

                jPanel1.setBackground(new java.awt.Color(0, 0, 0));
                jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Enter security question");

                usernameField.setBackground(new java.awt.Color(51, 51, 51));
                usernameField.setForeground(new java.awt.Color(255, 255, 255));

                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("Enter New Password");

                newPasswordField.setBackground(new java.awt.Color(51, 51, 51));
                newPasswordField.setForeground(new java.awt.Color(255, 255, 255));

                jLabel6.setBackground(new java.awt.Color(51, 51, 51));
                jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                jLabel6.setText("Enter Username");

                question_input.setBackground(new java.awt.Color(51, 51, 51));
                question_input.setForeground(new java.awt.Color(255, 255, 255));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 21, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(question_input, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(35, 35, 35))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(question_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                );

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, 200));

                changePasswordButton.setBackground(new java.awt.Color(0, 204, 51));
                changePasswordButton.setForeground(new java.awt.Color(255, 255, 255));
                changePasswordButton.setText("Change Password");
                changePasswordButton.setToolTipText("");
                changePasswordButton.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                changePasswordButtonMouseClicked(evt);
                        }
                });
                changePasswordButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                changePasswordButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(changePasswordButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

                jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                jLabel5.setText("Don't want to change password?");
                getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

                loginBtn.setBackground(new java.awt.Color(0, 153, 0));
                loginBtn.setForeground(new java.awt.Color(255, 255, 255));
                loginBtn.setText("Login");
                loginBtn.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                loginBtnActionPerformed(evt);
                        }
                });
                getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, -1, -1));

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GameImage/bg.png"))); // NOI18N
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 340));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
                  java.awt.EventQueue.invokeLater(() -> {
        new LoginPage().setVisible(true);
    });

    // Dispose the current MenuPage frame
    this.dispose();
    }//GEN-LAST:event_loginBtnActionPerformed

        private void changePasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordButtonActionPerformed
        }//GEN-LAST:event_changePasswordButtonActionPerformed

        private void changePasswordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePasswordButtonMouseClicked
	String username = usernameField.getText();
	String question = question_input.getText();
	String new_password = new String(newPasswordField.getPassword());

	if(username.isEmpty() || question.isEmpty() || new_password.isEmpty()){
		JOptionPane.showMessageDialog(this, "Field is blank!!", "Error", JOptionPane.INFORMATION_MESSAGE);
	}
	if (new_password.length() < 5) {
			JOptionPane.showMessageDialog(this, "Password must be at least 5 characters long", "Validation Error", JOptionPane.ERROR_MESSAGE);
			return;
		}

	boolean success = AuthenticationController.forgotPassword(username, question, new_password);

	if(success){
		JOptionPane.showMessageDialog(this, "password changed!!", "Success", JOptionPane.INFORMATION_MESSAGE);

}else {
		
		JOptionPane.showMessageDialog(this, "failed to change", "Error", JOptionPane.INFORMATION_MESSAGE);
	}
		
        }//GEN-LAST:event_changePasswordButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPasswordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgetPasswordPage().setVisible(true);
            }
        });
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton changePasswordButton;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JButton loginBtn;
        private javax.swing.JPasswordField newPasswordField;
        private javax.swing.JTextField question_input;
        private javax.swing.JTextField usernameField;
        // End of variables declaration//GEN-END:variables
}
