
import Database.AuthenticationController;
import Database.ScoreController;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class Leaderboard extends javax.swing.JFrame {

	
	public Leaderboard() {
		initComponents();
		populateProductTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                level_input = new javax.swing.JTextField();
                level_btn = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                leaderboard_table = new javax.swing.JTable();
                menuButton = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(0, 0, 0));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                level_input.setBackground(new java.awt.Color(51, 51, 51));
                level_input.setForeground(new java.awt.Color(255, 255, 255));
                level_input.setText("level");
                getContentPane().add(level_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 29, 196, -1));

                level_btn.setBackground(new java.awt.Color(0, 255, 51));
                level_btn.setForeground(new java.awt.Color(255, 255, 255));
                level_btn.setText("search");
                level_btn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                level_btnMouseClicked(evt);
                        }
                });
                getContentPane().add(level_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 29, -1, -1));

                leaderboard_table.setBackground(new java.awt.Color(51, 51, 51));
                leaderboard_table.setForeground(new java.awt.Color(255, 255, 255));
                leaderboard_table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null}
                        },
                        new String [] {
                                "username", "final_score", "level"
                        }
                ));
                jScrollPane1.setViewportView(leaderboard_table);

                getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 396, 304));

                menuButton.setBackground(new java.awt.Color(0, 0, 0));
                menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mainMenuButton.png"))); // NOI18N
                menuButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                menuButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 56, -1));

                jPanel1.setBackground(new java.awt.Color(0, 0, 0));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 410, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 370, Short.MAX_VALUE)
                );

                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 370));

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void level_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level_btnMouseClicked
                // TODO add your handling code here:
		String level = level_input.getText();
		
		List<ScoreController.LeaderboardEntry> score = ScoreController.getLeaderboardByLevel(level,AuthenticationController.getUserId() );

		String[] columnNames = {
			"username", "score", "level"
		};

		DefaultTableModel model = new DefaultTableModel(columnNames, 0);

		for (ScoreController.LeaderboardEntry scores : score) {
			Object[] rowData = {
				scores.getUsername(),
				scores.getScore(),
				scores.getLevel(),
			};
			model.addRow(rowData);
		}

		 leaderboard_table.setModel(model);
		
        }//GEN-LAST:event_level_btnMouseClicked

        private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
                // TODO add your handling code here:
		new MenuPage().setVisible(true);
		this.dispose();
        }//GEN-LAST:event_menuButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	private void populateProductTable() {

		List<ScoreController.LeaderboardEntry> score = ScoreController.getAllLeaderboardData(AuthenticationController.getUserId());

		String[] columnNames = {
			"username", "score", "level"
		};

		DefaultTableModel model = new DefaultTableModel(columnNames, 0);

		for (ScoreController.LeaderboardEntry scores : score) {
			Object[] rowData = {
				scores.getUsername(),
				scores.getScore(),
				scores.getLevel(),
			};
			model.addRow(rowData);
		}

		 leaderboard_table.setModel(model);

	}

	

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Leaderboard().setVisible(true);
			}
		});
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable leaderboard_table;
        private javax.swing.JButton level_btn;
        private javax.swing.JTextField level_input;
        private javax.swing.JButton menuButton;
        // End of variables declaration//GEN-END:variables
}
