
import Database.AuthenticationController;
import Database.ScoreController;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class Leaderboard extends javax.swing.JFrame {

	
	public Leaderboard() {
		initComponents();
		populateProductTable();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                level_input = new javax.swing.JTextField();
                level_btn = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                leaderboard_table = new javax.swing.JTable();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                level_input.setText("level");

                level_btn.setText("search");
                level_btn.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                level_btnMouseClicked(evt);
                        }
                });

                leaderboard_table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null},
                                {null, null, null},
                                {null, null, null},
                                {null, null, null}
                        },
                        new String [] {
                                "username", "final_score", "level"
                        }
                ));
                jScrollPane1.setViewportView(leaderboard_table);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(level_input, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(level_btn)
                                .addContainerGap(62, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(level_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(level_btn))
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE))
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void level_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_level_btnMouseClicked
                // TODO add your handling code here:
		String level = level_input.getText();
		
		List<ScoreController.LeaderboardEntry> score = ScoreController.getLeaderboardByLevel(level,AuthenticationController.getUserId() );

		String[] columnNames = {
			"username", "score", "level"
		};

		DefaultTableModel model = new DefaultTableModel(columnNames, 0);

		for (ScoreController.LeaderboardEntry scores : score) {
			Object[] rowData = {
				scores.getUsername(),
				scores.getScore(),
				scores.getLevel(),
			};
			model.addRow(rowData);
		}

		 leaderboard_table.setModel(model);
		
        }//GEN-LAST:event_level_btnMouseClicked

	/**
	 * @param args the command line arguments
	 */
	private void populateProductTable() {

		List<ScoreController.LeaderboardEntry> score = ScoreController.getAllLeaderboardData(AuthenticationController.getUserId());

		String[] columnNames = {
			"username", "score", "level"
		};

		DefaultTableModel model = new DefaultTableModel(columnNames, 0);

		for (ScoreController.LeaderboardEntry scores : score) {
			Object[] rowData = {
				scores.getUsername(),
				scores.getScore(),
				scores.getLevel(),
			};
			model.addRow(rowData);
		}

		 leaderboard_table.setModel(model);

	}

	

	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Leaderboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Leaderboard().setVisible(true);
			}
		});
	}


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable leaderboard_table;
        private javax.swing.JButton level_btn;
        private javax.swing.JTextField level_input;
        // End of variables declaration//GEN-END:variables
}
